name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install V, git and GCC
      run: |
        sudo apt update
        sudo apt install -y git gcc clang make \
          libgc-dev libxi-dev libxcursor-dev \
          libgl1-mesa-dev libegl1-mesa-dev mesa-common-dev xorg-dev libasound-dev
        git clone --depth 1 https://github.com/vlang/v.git ~/v
        (cd ~/v;make -j 4;sudo ./v symlink)
        echo "---"
        which v;pwd;v doctor
        echo "---"
        ln -s $(pwd) /home/$(whoami)/.vmodules/vmujs
        ls /home/$(whoami)/.vmodules/

    - name: Run TCC Tests
      run: |
        v -stats test ~/.vmodules/vmujs/tests/

    - name: Run GCC Tests
      run: |
        v -stats test ~/.vmodules/vmujs/tests/

    - name: Run Clang Tests
      run: |
        v -stats test ~/.vmodules/vmujs/tests/

    - name: Build examples
      run: |
        cd examples;./build_examples.sh
