name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install V, git and GCC
      run: |
        sudo apt install -y git gcc clang libgc-dev
        git clone --depth 1 https://github.com/vlang/v.git ~/v
        (cd ~/v;make -j 4;sudo ./v symlink)
        which v;pwd;v doctor

    - name: Run TCC Tests
      run: |
        ln -s $(PWD) /Users/$(whoami)/.vmodules/vmujs
        cd vmujstests;v -stats test .

    - name: Run GCC Tests
      run: |
        ln -s $(PWD) /Users/$(whoami)/.vmodules/vmujs
        cd vmujstests;v -stats -cc gcc test .

    - name: Run Clang Tests
      run: |
        ln -s $(PWD) /Users/$(whoami)/.vmodules/vmujs
        cd vmujstests;v -stats -cc clang test .
